version: '3.8' # Specifies the Docker Compose file format version

services:
  sim_frontend:
    build:
      context: .
    image: sim_frontend:latest
    container_name: sim_frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    restart: unless-stopped
