[project]
name = "sim-frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.8"
dependencies = [
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "nest-asyncio>=1.6.0",
    "python-dotenv>=1.1.0",
    "streamlit>=1.45.1",
    "websockets>=15.0.1",
]
